apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ include "hcm.namespace" . }}
spec:
  selector:
    app: {{ include "hcm.fullname" . }}-backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  type: ClusterIP
