apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hcm.fullname" . }}-frontend
  namespace: {{ include "hcm.namespace" . }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "hcm.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "hcm.fullname" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          imagePullPolicy: {{ .Values.images.frontend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
