apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hcm.fullname" . }}-postgres
  namespace: {{ include "hcm.namespace" . }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ include "hcm.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "hcm.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.images.postgres.repository }}:{{ .Values.images.postgres.tag }}"
          imagePullPolicy: {{ .Values.images.postgres.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "hcm.fullname" . }}-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "hcm.fullname" . }}-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "hcm.fullname" . }}-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "hcm.fullname" . }}-postgres-pvc
        - name: postgres-init
          configMap:
            name: {{ include "hcm.fullname" . }}-postgres-init
