apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hcm.fullname" . }}-postgres-init
  namespace: {{ include "hcm.namespace" . }}
data:
  init.sql: |
{{ .Values.postgresInitSql | nindent 4 }}
