apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hcm.fullname" . }}-secrets
  namespace: {{ include "hcm.namespace" . }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | quote }}
